### ISSUE TITLE
API urls not sanitised during first setup

### ISSUE THREAD

**Issue by jenswegar** [PaloAltoNetworks/prismacloud-cli#68]
## Describe the bug

When first running the cli tool after installing, it asks for API urls. However, if I paste a URL with https:// in it, it will be stored to config as such, but subsequent requests to the API fail.

## Expected behavior

The setup flow should sanitise the url to such a form that it works regardless if the value contains the protocol or not. Alternatively, URL's read from the config json should be sanitised to the expected form before the calls to the API.

## Current behavior

Requests fail because the URL stored in the config is in the wrong format. Log output:

```
Traceback (most recent call last):
  File "/Users/xyz/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/xyz/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/xyz/Library/Python/3.9/lib/python/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //api.eu.prismacloud.io/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x125250b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))


```

## Steps to reproduce

starting from a fresh install
1. ```pip3 install prismacloud-cli```
2. ```pc version```
3. follow steps to setup tool, but set API urls including https, e.g. https://api.eu.prismacloud.io
4. Once done, requests fail

Alteratively just change the URL's in ```~/.prismacloud/credentials.json``` to include ```https://``` and try to call ```pc version```. Request will fail.

## Your Environment

- Version used: prismacloud_cli-0.4.35
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python 3.9
- Operating System and version (desktop or mobile): MacOS 12.4

**Comment by tkishel** [comment]
PR submitted.

**Comment by tkishel** [comment]
Merged
