### ISSUE TITLE
pc -v audits container

### ISSUE THREAD

**Issue by sgordon46** [PaloAltoNetworks/prismacloud-cli#81]
## Describe the bug

I'd like to use the cli tool to export container audits

## Expected behavior

I would expect ` pc -v audits container` to return back the audits from the container runtime. 

## Current behavior

But it is returning nothing, and when reviewing the source code, I see `audits/firewall/app/container` the following API being called which is for WAAS and not container runtime. 

## Possible solution

I would suggest we update this endpoint or create a new option for this result. 

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by dukekautington3rd** [comment]
PR #82 submitted yesterday

**Comment by sgordon46** [comment]
@dukekautington3rd Thanks for this. I guess we're waiting for approval now.

**Comment by steven-deboer** [comment]
Closing this one as it has been fixed, thanks @dukekautington3rd and @sgordon46!
