### ISSUE TITLE
How do I enter the criteria for CWPP API query parameter, search?

### ISSUE THREAD

**Issue by citrusoft** [PaloAltoNetworks/prismacloud-cli#88]
## Documentation link

https://prisma.pan.dev/api/cloud/cwpp/registry#operation/get-registry-download

## Describe the problem

accuracy?  request for improvement

Given above documentation,  how would / do I specify the search criteria for this API invocation?
https://github.com/PaloAltoNetworks/prismacloud-cli/blob/39b60c85882919f1d12115c29f0b5123622e8f88/prismacloud/cli/cwpp/cmd_scans.py#L12

## Suggested fix

Why don't someone create a tutorial / examples of the CWPP API query parameters?
fields, search and offset + limit are good to know.

**Comment by steven-deboer** [comment]
Hi @citrusoft,

`--help` is your friend here. If you use

`pc --config local scans --help`

You'll get information on those parameters.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/96180461/201606065-95445275-1fed-4cf6-ad27-dc91460e8d0b.png">
